app = "maintenance-tasks-ui"

[env]
  RAILS_ENV = "production"
  PORT = "8080"
  SOLID_QUEUE_IN_PUMA = "1"

[http_service]
  internal_port = 8080
  force_https = true
  min_machines_running = 0

[deploy]
  release_command = "bin/rails db:prepare"
